# EXERCISE INSTRUCTIONS
# This script should output a list of column names from a CSV file with any spaces replaced by underscores (the '_' character)
# This script was started by someone else, and you've been asked to fix any errors and provide this functionality

# Fork the repository to your GitHub account, clone the repository on your laptop and then make changes to the code following the instructions below

data = pandas.read_csv("weather_data/weatheryear.csv")

col_names = data.columns.values.tolist()
print col_names

# STEP 1 - Define a function below called "replace_whitespace" that can replace characters in a string with another character specified in the function parameter. The function should take two parameters, the first being the string that needs whitespace characters replacing, and the second being the character to insert instead of the whitespace. The keyword argument for the replacement character should be the '_' character.



# STEP 2 - print the new column names generated by running your replace_whitespace function
# BONUS - trim any leading (at the front of the string) or trailing (at the end) whitespace characters from each column name before you call your replace_whitespace function


# STEP 3 - once you're ready, commit the changes, push them to your repository and create a pull request to Aleksandra's repository which you originally forked. 
